class AppRoutes {
  static const String splashPageRoute = "/",
      onBoardingRoute = "OnBoardingScreen",
      loginRoute = "LoginScreen",
      registerPageRoute = "registerScreen",
      jobsPageRoute = "jobsScreen",
      RegisterSuccessPageRoute = "RegisterSuccessScreen",
      LoginPageRoute = 'LoginPaeg',
      restPasswordPageRoute = 'ResetPasswordScreen',
      checkEmaailPageRoute = 'checkEmailScreen',
      createNewPasswordPageRoute = 'createNewPasswordScreen',
      homePageRoute = 'homePageScreen',
      resetSucceededRoute = 'resetSucceededScreen',
      layoutRoute = 'LayoutScreen',
      searchRoute = 'SearchScreen',
      jobDetailRoute = 'jobDetailsScreen',
      messagesRoute = 'MessagesScreen',
      stepperRoute = 'stepperScreen',
      notificationRoute = 'notificationScreen',
      applySuccessRoute = 'ApplyScreen',
      locationPageRoute = "locationScreen";
}
